### ISSUE TITLE
Trouble building Cedille from source distribution

### ISSUE THREAD

**Issue by cwjnkins** [cedille/cedille#109]
Currently on our [releases page](https://github.com/cedille/cedille/releases) our source code distributions (.zip and .tar.gz) both contain sub-directories for the IAL which are empty. Currently the Makefile assumes that it will always be invoked within a git repository and so tries to populate these subdirectories with a submodule command. Trying compile Cedille from just these source distributions results in the following error:
```
git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git
Makefile:102: recipe for target 'ial/ial.agda-lib' failed
make: *** [ial/ial.agda-lib] Error 128
```

**Comment by astump** [comment]
In Cedille meeting, we are thinking maybe we should just include the ial in the source distribution for the release.  The Makefile could check if ial is there, and not invoke git submodule init if it is.
