### ISSUE TITLE
add an option (in options file) to disable conversion checking

### ISSUE THREAD

**Issue by astump** [cedille/cedille#127]
For investigations into performance, let us implement an option that disables conversion checking, and instead just says everything is convertible to everything.

This might occasionally be useful independent of performance testing.

Probably we should flag to the user that this option is being used, in case they forget it in their options file.  Maybe highlight the module span?

**Comment by cantora** [comment]
Results comparison: type-checking stdlib.ced 60 times takes 29.87 seconds / 36.34 seconds when conversion checking is disabled / enabled, respectively.

With the method I used to disable conversion checking, the delta and sigma functions were broken, so these facts may have affected the time comparison. The issue that arose with sigma was that cedille could not compute a motive in certain situations. For example in line 16 of wksigma it says "We could not compute a well-kinded motive".

**Comment by astump** [comment]
Hi, Tony.  This is very interesting, and clearly was a valuable 
experiment: it looks like conversion checking is not taking as big a 
percentage of our time as I would have guessed.  Thanks very much for 
these results.
Aaron
