### ISSUE TITLE
Typo in Cedille core description document

### ISSUE THREAD

**Issue by JanBessai** [cedille/cedille#140]
The [core description](https://github.com/cedille/cedille.github.io/blob/master/semantics.pdf) has a typo in the first rule of Figure 3:

```
(x: t) in Gamma
-----------------------
Gamma |- x => T
```
should use `T` instead of `t` in its premise.

~~In rule~~
```
Gamma |- FV(t) subseteq dom(Gamma)
-----------------------------------------------------
Gamma |- beta{t'} <= { t cong t }
```
~~Term `t'` does not appear anywhere. Should this be t? The same is true for the bullet point explaining the rule.~~ 
Edit: This is fine, it's the trick.

Also in Section 2.2:
- "In our annotated syntax, we write {t}" does not make sense-  should this be `beta{t}`?
- "delta x has type { x  . x x . x x}" seems to be lacking some lambdas and a cong. The sentence also seems odd: what is `x` in `delta x`? Should this be relative to a context? Term `id` hasn't been previously declared (which should be done to include the quantification over types). In the typewriter text, "X : . X X" a quantifier is missing.

**Comment by JanBessai** [comment]
Thanks for the patch.

I just noticed that the erasure function is ill-specified for Lambda binders:
```
|Lambda x . t' t| = |t|
```
should be
```
|Lambda x . t| = |t|
```
c.f. your [current paper](https://homepage.cs.uiowa.edu/~astump/papers/from-realizability-to-induction-aaron-stump.pdf)

**Comment by cwjnkins** [comment]
Hi, Jan,

Good catch, thanks! The most recent document
<https://github.com/cedille/cedille/blob/master/docs/semantics/paper.pdf>
should have this fixed now.
