### ISSUE TITLE
stack installation puts cedille executable in base directory

### ISSUE THREAD

**Issue by bmyerz** [cedille/cedille#142]
After completing the [stack build](https://cedille.github.io/BUILD.html), the cedille executable is placed in the base directory.

However, when in emacs I start cedille mode (in this case with M-x cedille-mode), it looks for bin/cedille.

The problem appears to be fixed by making a bin/ and moving the executable to it. Is this something that the stack build should do?

**Comment by amarmaduke** [comment]
Hey @bmyerz I simplified the build process to make this hopefully less confusing in the future, now you can just run `stack install` and don't have to worry about passing the arguments yourself.

The build instructions you linked are for Cedille 1.1.2 which requires the cedille binary to be in a different directory than the master branch does, that's the source of the inconsistency between what master expects and what those instructions claim.
