### ISSUE TITLE
Byte compilation problem

### ISSUE THREAD

**Issue by Apteryks** [cedille/cedille#160]
Hello,

Attempting to byte compile the Elisp libraries shipped with Cedille, I get:

```
emacs "--batch" "--eval=(eval '(progn (setq byte-compile-debug t) (byte-recompile-directory (file-name-as-directory \".\") 0 1)) t)"
Checking /tmp/guix-build-cedille-1.1.2.drv-2/source/...
Compiling /tmp/guix-build-cedille-1.1.2.drv-2/source/cedille-mode.el...

In toplevel form:
cedille-mode.el:16:30:Warning: Package cl is deprecated
Symbol’s value as variable is void: cedille-path-el
```
I've isolated (by commenting out parts of the code) that the problem comes from the following line:
```
(require 'cedille-mode-library)
```
in the root directory `cedille-mode.el` file (line 90).

I'm not just why that is or how to solve it, but I thought I'd report it here.

Thanks!

**Comment by astump** [comment]
Thanks a lot for this bug report, Apteryks.  Yes, byte-compilation of the .el files for Cedille is not working, I think.  Something we will try to correct in the next version -- though development will likely not start on that until the summer (2021)?

**Comment by Apteryks** [comment]
Thank you for the prompt feedback.  For the record, byte compilation worked for all files except `cedille-mode.el`, `cedille-mode/cedille-mode-library.el` and `se-mode/se-hole.el`.
