### ISSUE TITLE
build failure with Agda 2.5.3 

### ISSUE THREAD

**Issue by samuelgruetter** [cedille/cedille#25]
OS: Fedora 28
Agda version 2.5.3, installed using Fedora's package manager.
Cedille version: Tried both ef1103120eaef10dd4b61bfb9575e9e527ed728a (current master) and 6734731 (v1.0.0)
I followed https://cedille.github.io/BUILD.html, but `make` failed with the following error:

```
/home/sam/Documents/git/clones/cedille/src/meta-vars.agda:337,38-45
Cannot eliminate type _C_475 options Γ with pattern xs (did you
supply too many arguments?)
when checking that the pattern nothing has type
maybe (meta-var-sol type)
make: *** [Makefile:109: cedille] Error 1
```

**Comment by samuelgruetter** [comment]
(also, as a suggestion, adding travis to a github repo is a very simple way to convince others that your code actually compiles :wink: And helps users to see which versions of the dependencies will work. It's as easy as adding a `.travis.yml` file with a few lines of config (see mine [here](https://github.com/mit-plv/bedrock2/blob/master/.travis.yml) for example), and enabling the travis app in the settings page of the github repo)

**Comment by larrytheliquid** [comment]
Unfortunately I think (but am not sure) the answer might be that we only support Agda 2.5.4.

One downside of developing software in Agda is that you are tied to particular versions,
because the pragmas/bindings to primitive datatypes change between versions.
There isn't a good solution in Agda to support different pragmas (old and new) for
different Agda versions.

**Comment by cwjnkins** [comment]
Hi, Samuel.

What @larrytheliquid said is correct -- we are using Agda 2.5.4 and that is the recommended version for compiling Cedille from source. I have tried compiling Cedille with 2.5.3 but it breaks at the backwards-incompatible changes Agda has made for some pragmas.

To use this version of Agda to compile you will also need to upgrade your version of the ial to 1.5 (simply checking out the latest master will do the trick -- I know by your error message that you must be using 1.4 currently). You can find instructions on installing Agda from cabal [here](https://agda.readthedocs.io/en/v2.5.4/getting-started/installation.html) -- but it probably requires either removing or being very clever about hiding the version of Agda install through the system package manager.

**Comment by samuelgruetter** [comment]
I see. So https://cedille.github.io/BUILD.html should probably be updated to replace "Agda version 2.5.x" by "Agda version 2.5.4", and "git checkout v1.4.0" with "git checkout v1.5.0" or so

**Comment by cwjnkins** [comment]
The documentation has been updated accordingly.
