### ISSUE TITLE
Implicit / Irrelevant Let

### ISSUE THREAD

**Issue by cwjnkins** [cedille/cedille#43]
module issue-43.
    
    import cast.

Right now, let bindings are always considered relevant. This is somewhat
annoying when you want to try to make a local binding for an irrelevant term.

In the example below `c'` is only used irrelevantly, but the occurence checker
 still treats it as relevant and produces an error

    castSilly : ∀ A: ★. ∀ B: ★. Cast ·A ·B ➾ Cast ·A ·B
      = Λ A. Λ B. Λ c.
        [ c' = c ] - [ λ a. cast -c' a , β ].

I do *not* propose that we do any kind of analysis for local definitions to
see if, when we use an irrelevant variable, it only occurs irrelevantly.
Instead, I think the most sensible thing to do is introduce new syntax for
such bindings

    castSilly : ∀ A: ★. ∀ B: ★. Cast ·A ·B ➾ Cast ·A ·B
      = Λ A. Λ B. Λ c.
        { c' = c } - [ λ a. cast -c' a , β ].

Which follows the same syntactic conventions as implicit module imports.

**Comment by astump** [comment]
We have considered this idea a bit in the past -- and I think it is a very good one!  This could be a nice project for someone looking to take on a pretty bounded project for Cedille engineering, like maybe @cantora?  The proposed syntax seems appealing based on fitting with the module parameter syntax.

**Comment by cwjnkins** [comment]
@astump Actually, thinking about this a bit more, I have a counter-proposal: Since curly-braces indicated some type of "untyped" setting (equality, beta, phi), maybe it would be better instead to use the dash -- after all, when we add notation for datatypes the current proposal is to use a dash like

    | vcons -n x xs ->

to indicate that `n` is bound implicitly. So then an implicit let would look like

    [ -c' = c] - [ λ a. cast -c' a , β ].

**Comment by cantora** [comment]
@astump Sure, this sounds like something I could work on.

**Comment by cwjnkins** [comment]
For documentation purposes: we discussed this today and concluded that the (optional) syntax we should go with for implicit lets is curly braces.
