### ISSUE TITLE
Jumping to definitions not working

### ISSUE THREAD

**Issue by larrytheliquid** [cedille/cedille#44]
Seems like the tags table is not getting generated. When I try to jump I get the error:
`TAGS does not exist.`

Can someone else confirm this or is it just me? @HerbertMcSnout 

Not sure if its related, but I noticed that `make` now compiles the elisp code, maybe that broke something?

**Comment by cwjnkins** [comment]
Jump functionality is working for me on 9cf3021 (branch issue-38, which should be consistent with master), including jumping to definitions in the same file and in an imported one. I just recently re-compiled and restarted Emacs (which should reload Cedille mode), so perhaps try that? If not, probably need the commit hash to re-create the issue.

**Comment by HerbertMcSnout** [comment]
Hmm... I think emacs has some notion of "jumpable" tags, but we implement a custom one instead. I get a message like that if I'm in some non-cedille/agda/elisp mode and hit "M-.". So maybe try recompiling the elisp code?
