### ISSUE TITLE
Spans for occurs-check errors

### ISSUE THREAD

**Issue by cwjnkins** [cedille/cedille#49]
Currently, when an implicitly bound variable occurs free in the body of an expression, the entire expression (starting with the binding site) gets underlined with an error span. Such error reporting would be much less cluttered (but just as effective) if the error span was report just at the binding site of the variable. For example:

    f : ∀ X: ★. X ➾ X ➔ X
      = Λ X. Λ x. λ y. [ id : X ➔ X = λ z. z ] - id x.
    -- Now   ^--------------------------------------^
    -- New     ^

**Comment by HerbertMcSnout** [comment]
@amarmaduke Are you referencing an error where you check an unerased lambda term against a type forall (so "∀ X : [kind]. ...")? If so, the error is only there to stop users from checking unerased lambda terms against type **pi**s (Π X : [kind]. ...):
`contra-h : Π X : ★. (ι id : X ➔ X. {id ≃ λ x. x}) = λ X. [λ x. x, β].`
`contra = δ - χ {λ X. λ x. x ≃ λ x. x} - (test · {λ x. x ≃ λ x. x}).2.`

Or do you mean some other error?

**Comment by amarmaduke** [comment]
This example will have two errors on master:

```
f : ∀ X : ★. X ➔ X ➔ X
  = λ X. λ x. λ y. x.
```

One will be on the span containing the entire lambda term, and one on the span containing just X. It seems like the error is more general then intended? We can talk more about it on Monday since its not a high priority thing.
