### ISSUE TITLE
Expand Occurs check for Let-bound Variable

### ISSUE THREAD

**Issue by cwjnkins** [cedille/cedille#50]
Relates to issue #43. Optionally, instead of providing an explicit annotation for implicit lets, we could expand the occurs checker so that it can automatically detects whether or not a let-bound variable occurs only in erased positions.

When checking (in classify.agda) that a Λ-bound variable does not occur free in the body, function `is-free-in` is invoked. `is-free-in` should be modified so that in cases where it is inspecting a let-binding, if a Λ-bound variable occurs in the erasure of the definition of the let-bound variable, it must be the case that the let-bound variable **does not** occur in the erasure of the body of the let expression.

Additionally, in the case that an error is generated due to an erased argument occurring in an unerased position, we should ensure that what is reported to the user is intelligible. Namely, the erasure of an expression which contains an erasable let-bound variable _should not have that binding in it_ , but _should_ show the bound variable somewhere in the body.

**Comment by cwjnkins** [comment]
@cantora Corner case with name shadowing in the skip-erased case. Otherwise I think this should do the trick!

**Comment by cantora** [comment]
Reopening this issue because I still need to take care of the erasure of terms: if a term has a let binding such that the bound variable only occurs in erased positions, then when we erase that term we must also erase the let binding itself.

**Comment by HerbertMcSnout** [comment]
If I remember correctly, our is-free-in algorithm actually never calls the `erase` functions. So maybe we just need to move `erase` to `src/is-free.agda` after `is-free-in`, and then in the `Let` case of `erase-term` write `if (is-free-in skipErased x t') then Let (DefTerm ... x t) t' else t'`?

**Comment by cantora** [comment]
@HerbertMcSnout Yeah `is-free` doesn't call the erase functions, so I ended up making a new `erase` module, and modified the erase function in a manner similar to your suggestion. If you have time, please take a look and let me know if you see any issues. Thanks!

**Comment by cantora** [comment]
This is now merged into master
