### ISSUE TITLE
Build failure with debain system installed Agda

### ISSUE THREAD

**Issue by kyagrd** [cedille/cedille#53]
I have system installed Agda in Debian.
```
kyagrd@kyaGr:~/github/cedille/cedille$ which agda
/usr/bin/agda
kyagrd@kyaGr:~/github/cedille/cedille$ agda --version
Agda version 2.5.4.1
```
 So I just ran make but fails trying to find MAlonzo directory in the wrong place like below.
```
...
Compiling main in /home/kyagrd/github/cedille/cedille/src/main.agdai to /home/kyagrd/github/cedille/cedille/src/MAlonzo/Code/Qmain.hs
agda: /usr/share/libghc-agda-dev/MAlonzo/src: getDirectoryContents:openDirStream: does not exist (No such file or directory)
make: *** [Makefile:112: cedille] error 1
```

Both master and release-1.0 branch failed with the same error.

**Comment by cwjnkins** [comment]
@kyagrd This is a shot in the dark but try the commit I just pushed (branch issue-53). On my machine, it changes the invocation of Agda from

    agda --library-file=libraries --library=ial --library=cedille --ghc-flag=-rtsopts -c src/main.agda

to

    agda --library-file=libraries --library=ial --library=cedille --ghc-flag=-rtsopts -c /home/christopher/vc/cedille/src/main.agda

On my machine both versions end up invoking GHC with the correct (absolute) path, but maybe the Debian Agda does things differently?

If that doesn't work, please run `make SHELL="bash -x"' and give the full output here.

**Comment by kyagrd** [comment]
@cwjnkins It's pretty much the same. Maybe Agda debain packaging has some problems. Similar thing happens in other project using MAlonzo in their directory.

I'll include "bash -x" version of my output here

```
kyagrd@kyaGr:~/github/cedille/cedille$ make SHELL="bash -x"
agda --library-file=libraries --library=ial --library=cedille --ghc-flag=-rtsopts --ghc-flag=-dynamic -c src/main.agda
+ agda --library-file=libraries --library=ial --library=cedille --ghc-flag=-rtsopts --ghc-flag=-dynamic -c src/main.agda
agda: /usr/share/libghc-agda-dev/MAlonzo/src: getDirectoryContents:openDirStream: does not exist (No such file or directory)
make: *** [Makefile:112: cedille] 오류 1
```

**Comment by astump** [comment]
This sounds like some issue with how Agda has gotten installed from the Debian package.  So maybe an issue for Agda?

Did you try installing Agda with just "cabal install Agda"?

**Comment by kyagrd** [comment]
This seem to be a common problem. Hit the exactly same bug in POPL TutorialFest's Agda session.
For me, leaving the Debian system package as it is but "stack install Agda" (making sure that version is the same as Debian system installed Agda) and configure .agda directory to use the system installed agda-stdlib, fixed the problem. At least one can use system installed Agda standard library.

Debian system installed Agda seem to have problems with compiling through ghc for executable. I think this may be more appropriate to report to Agda debian maintainers.

**Comment by aryzach** [comment]
I'm having the same problem. I have agda 2.5.3, and agda-stdlib-0.15, which I believe is the correct standard library. If it's not an executable (agda hello.agda) it's ok, but the executable (agda -c hello.agda) 

My result is the same as yours:
`agda: /usr/share/libghc-agda-dev/MAlonzo/src: getDirectoryContents:openDirStream: does not exist (No such file or directory)`

looks like a agda issue though and not stdlib, because of the /usr/share/libghc-agda-dev, and I have my standard library elsewhere. I could be wrong though. Also I'm using GalliumOS for various reasons. 

Any ideas?
