### ISSUE TITLE
Pattern matching bug when datatype parameter is instatiated with the datatype itself

### ISSUE THREAD

**Issue by cwjnkins** [cedille/cedille#56]
See `issues/issue-54.ced` on branch `datatype-staging`

    data List (A: ★) : ★ =
      | nil  : List
      | cons : A ➔ List ➔ List
      .
    
    append : ∀ A: ★. List ·A ➔ List ·A ➔ List ·A
      = Λ A. λ xs. λ ys. μ append-ys. xs {
      | nil ➔ ys
      | cons x xs ➔ cons x (append-ys xs)
      }.
    
    concat : ∀ A: ★. List ·(List ·A) ➔ List ·A
      = Λ A. λ xss. μ concat. xss {
      | nil ➔ nil ·A
      | cons xs xss ➔ append xs (concat xss)
      }. --                  ^^
         -- expected-type: List ·A
         --          type: concat/type

Essentially what's happening is that when typing the bound pattern variables, type `List` is being substituted away by `λ A: ★. concat/type`. This is happening *after* parameter instantiation, of course, so if branch label `cons`  "usually" has type `List ·A ➔ List ·(List ·A) ➔ List ·(List ·A)`, then here at this branch it has type

    cons : concat/type ➔ concat/type ➔ concat/type

when it should really have type

    List ·A ➔ concat/type ➔ List ·(List ·A)

I believe I made this very mistake in the specification, too!

**Comment by HerbertMcSnout** [comment]
Great catch! I'll fix it.
