### ISSUE TITLE
Statically Compile Cedille Core Executable

### ISSUE THREAD

**Issue by HerbertMcSnout** [cedille/cedille#65]
I believe we should statically compile the Cedille Core executable (cedille/core/CedilleCore) so that cdle-mode works the same universally. However, ghc just gives me this error:
`ghc CedilleCore.hs -static -optl-static -optl-pthread`

`/usr/lib/ghc/rts/libHSrts.a(Linker.o): In function 'internal_dlopen':`
`(.text+0x397): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking`

I have been scouring the internet over this, and it looks like this usually indicates that my Haskell libraries have been dynamically compiled, and to properly compile CedilleCore as a static executable it requires that all the libraries are likewise statically compiled. Does anyone know why Agda's transpiled Haskell code does not encounter this error? Any advice on how I should continue?

**Comment by astump** [comment]
Not sure if it is the same problem, but I had to add -dynamic in 
cedille/Makefile to calls to ghc, due to some unpleasant linker error 
that seemed to be related.
Aaron
