### ISSUE TITLE
Erased Module Parameters Not Causing Free-In-Erasure Error

### ISSUE THREAD

**Issue by HerbertMcSnout** [cedille/cedille#72]
For example, there is currently no error in a file like:
`module test (x : {λ x. x ≃ λ x. x}).`
`import foo x. -- Not causing error!`
`oops = x. -- Not causing error either!`

@larrytheliquid I think this used to get checked...? Maybe it stopped working when the difference between module parameters and kind parameters was removed?

**Comment by larrytheliquid** [comment]
Just to make sure, are you sure you didn't mean:
`module test {x : {λ x. x ≃ λ x. x}}.`

**Comment by HerbertMcSnout** [comment]
Oops, that's what I meant to type—sorry! I believe typed it correctly in Cedille, though ;).
