### ISSUE TITLE
Add erasures to .cdle format

### ISSUE THREAD

**Issue by astump** [cedille/cedille#76]
It would be nice to have .cdle files record the erasures of terms in some way.  A simple idea (Chris's) would be to follow each term definition by a proof that the term equals its erasure.

**Comment by HerbertMcSnout** [comment]
Do you think it would be sufficient if, for each toplevel term definition DEF, we simply surround it with `φ β - DEF { |DEF| }`?

**Comment by astump** [comment]
Yes, I think that would be adequate.
