### ISSUE TITLE
Bug in interactive normalization of mu/mu' expressions

### ISSUE THREAD

**Issue by cwjnkins** [cedille/cedille#77]
I apologize in advance that I couldn't come up with a smaller working example, since I couldn't recreate the issue with single-step normalizations in the interactive mode.

Below is a simple example of binary representations of numbers with two operations, successor (`bS`) and addition (`bAdd`)

    data BNat: ★ =
      | bZ: BNat
      | b2: BNat ➔ BNat
      | b2p: BNat ➔ BNat.

`bZ` encodes zero, `b2 b` encodes twice the number represented by `b`, `b2p b` encodes one plus twice the number encoded by `b`

    bS : BNat ➔ BNat
      = λ b. μ rec. b {
      | bZ ➔ b2p bZ
      | b2 b ➔ b2p (to/BNat -isType/rec b)
      | b2p b ➔ b2 (rec b)
      }.

    bAdd : BNat ➔ BNat ➔ BNat
      = λ a. μ rec. a {
      | bZ ➔ λ b. b
      | b2 a ➔ λ b. μ' b {
        | bZ ➔ b2 (to/BNat -isType/rec a)
        | b2 b ➔ b2 (rec a b)
        | b2p b ➔ bS (b2 (rec a b))
        }
      | b2p a ➔ λ b. μ' b {
        | bZ ➔ b2p (to/BNat -isType/rec a)
        | b2 b ➔ bS (b2 (rec a b))
        | b2p b ➔ b2 (bS (rec a b))
        }
      }.

The bug occurs in the code below -- there are no type errors, but if you use the interactive command to normalize `bTwo'` you get a stuck mu-expression that is scope-incorrect (a free variable occurs that seems to be orphaned by the `bAdd` mu-expression that occurs at one point in the scrutinee of the `bS` mu-expression)

    bOne = b2p bZ.
    bTwo = b2 bOne.
    bTwo' = bAdd bOne bOne.
    -- C-i n of bTwo' has a free variable `rec` in it
    
    eq2 : {bTwo ≃ bTwo'} = β.

The result of invoking `C-i n` on `bTwo'` is

    b2 (μ rec' . (rec' bZ bZ) { bZ ➔ b2p bZ | b2 b'' ➔ b2p b'' | b2p b'' ➔ b2 (rec' b'') })
    
Where the `rec'` occurring in the scrutinee `rec' bZ bZ` ought to itself have been a mu-expression (under two lambdas) convertible with `bAdd`

**Comment by HerbertMcSnout** [comment]
Hmm... Looking into it now

**Comment by HerbertMcSnout** [comment]
After copying-and-pasting your code and hitting `C-i n` on `bTwo'`, I just get `b2 (b2p bZ)` (which I think is correct?). Could your cedille executable possibly be out of date?
