### ISSUE TITLE
Discrepancy in Delta Typing Rule—Cedille vs. Cedille Core

### ISSUE THREAD

**Issue by HerbertMcSnout** [cedille/cedille#94]
Cedille and Cedille Core appear to be handling the type `T` in `δ T - t` differently—Cedille expects it to be a regular, well-kinded type, but Cedille Core expects it to be an erased type (which elaboration delivers). I don't see any reason why it should be erased, so I'm guessing I just misread the specification?
@astump

**Comment by astump** [comment]
Looking at the Cedille Core spec again, I am not sure why metavariable T 
is used some places instead of t.  I agree with your interpretation (in 
the absence of some other insight), that this is just meant to be an 
annotated expression, not some kind of special erased class.
Aaron
