### ISSUE TITLE
Improve performance of trie code

### ISSUE THREAD

**Issue by astump** [cedille/cedille#99]
Colin notes that we do lots of trie lookups in Cedille type-checking, and these require converting strings (which Agda compiles to Data.Text) to lists of characters.  Changing trie so it uses an index into a string could improve performance quite a bit.

**Comment by astump** [comment]
Suggest to create a new trie file.  Goal is to avoid converting strings to lists of chars.  Should just be able to index the string by a natural number.  Might need to dig into Agda stuff a little or else use Agda pragma to connect to Haskell function for getting the character at an index into an Agda string (i.e., Data.Text in Haskell).  For testing, can use standard library, disable .cede files.

**Comment by cantora** [comment]
The work towards this end was integrated into Cedille under [this feature branch](https://github.com/cedille/cedille/tree/feature-use-trie-fast).

The alternative implementation employed the haskell string fold functions via FFI, but unfortunately the performance seems to be very close to what it was before.
